from __future__ import annotations

import json
import os
import urllib.error
import urllib.request
from typing import Dict, List, Protocol

from .models import ProofCandidate


class ProviderError(RuntimeError):
    pass


class CandidateProvider(Protocol):
    name: str
    model: str

    def generate_candidates(self, context: Dict[str, object]) -> List[ProofCandidate]:
        ...


class DemoProvider:
    name = "demo"
    model = "deterministic"

    def generate_candidates(self, context: Dict[str, object]) -> List[ProofCandidate]:
        expected = context.get("expected_tactics") or []
        errors = context.get("errors") or []
        if isinstance(expected, list) and expected:
            return [
                ProofCandidate(
                    proof="\n".join(str(step) for step in expected),
                    rationale="Use expected tactics from the curated benchmark metadata.",
                )
            ]
        if errors:
            return [ProofCandidate(proof="trivial", rationale="Fallback repair for simple goals.")]
        return [ProofCandidate(proof="trivial", rationale="Fallback proof for simple propositions.")]


class OpenAICompatibleProvider:
    name = "openai_compatible"

    def __init__(self, model: str = "", api_key: str | None = None, base_url: str | None = None) -> None:
        self.model = model or os.getenv("OPENAI_MODEL", "gpt-4o-mini")
        self.api_key = api_key or os.getenv("OPENAI_API_KEY", "")
        self.base_url = (base_url or os.getenv("OPENAI_BASE_URL", "https://api.openai.com/v1")).rstrip("/")
        if not self.api_key:
            raise ProviderError("OPENAI_API_KEY is not configured")

    def generate_candidates(self, context: Dict[str, object]) -> List[ProofCandidate]:
        prompt = (
            "Return only a Lean tactic proof body for this theorem.\n\n"
            f"Imports:\n{context.get('imports', '')}\n\n"
            f"Statement:\n{context.get('statement', '')}\n\n"
            f"Recent Lean errors:\n{context.get('errors', [])}"
        )
        payload = {
            "model": self.model,
            "messages": [
                {"role": "system", "content": "You write concise Lean 4 proof bodies."},
                {"role": "user", "content": prompt},
            ],
            "temperature": 0.2,
            "n": 1,
        }
        request = urllib.request.Request(
            f"{self.base_url}/chat/completions",
            data=json.dumps(payload).encode("utf-8"),
            headers={"Authorization": f"Bearer {self.api_key}", "Content-Type": "application/json"},
            method="POST",
        )
        try:
            with urllib.request.urlopen(request, timeout=45) as response:
                data = json.loads(response.read().decode("utf-8"))
        except (urllib.error.URLError, TimeoutError, json.JSONDecodeError) as exc:
            raise ProviderError(f"Provider request failed: {exc}") from exc
        content = data["choices"][0]["message"]["content"].strip()
        return [ProofCandidate(proof=_strip_fences(content), rationale="Generated by OpenAI-compatible provider.")]


def _strip_fences(text: str) -> str:
    if text.startswith("```"):
        lines = text.splitlines()
        if lines and lines[0].startswith("```"):
            lines = lines[1:]
        if lines and lines[-1].strip() == "```":
            lines = lines[:-1]
        return "\n".join(lines).strip()
    return text


def get_provider(name: str, model: str = "") -> CandidateProvider:
    if name == "demo":
        return DemoProvider()
    if name in {"openai", "openai_compatible"}:
        return OpenAICompatibleProvider(model=model)
    raise ProviderError(f"Unknown provider {name!r}")

